/**
 * Assistant module mock data
 */

import { AssistantTask, AIToolConfig, AssistantNotification } from './assistantTypes';

const daysFromNow = (days: number) =>
  new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export const ASSIGNED_TASKS: AssistantTask[] = [
  {
    _id: 'AT-2401',
    title: 'Background Lineart — Scene 3',
    type: 'Background',
    status: 'ASSIGNED',
    chapter: 'Ch. 12',
    chapterNumber: 12,
    series: 'Neon Genesis',
    deadline: daysFromNow(1),
    urgency: 'critical',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Complete detailed background lineart for the rooftop confrontation scene. Focus on city skyline depth and atmospheric perspective.',
    progress: 0,
  },
  {
    _id: 'AT-2402',
    title: 'Character Inking — Hiro',
    type: 'Character',
    status: 'IN_PROGRESS',
    chapter: 'Ch. 12',
    chapterNumber: 12,
    series: 'Neon Genesis',
    deadline: daysFromNow(3),
    urgency: 'warning',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Ink the protagonist Hiro in panels 2 and 4. Maintain consistent line weight with reference sheet provided.',
    progress: 45,
  },
  {
    _id: 'AT-2403',
    title: 'Speed Lines & FX',
    type: 'Effects',
    status: 'REVISING',
    chapter: 'Ch. 11',
    chapterNumber: 11,
    series: 'Cyberpunk Drifter',
    deadline: daysFromNow(2),
    urgency: 'warning',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Revise speed line density in action sequence. Mangaka feedback: reduce clutter in panel 3, add motion blur to panel 5.',
    progress: 70,
  },
  {
    _id: 'AT-2404',
    title: 'Dialogue Bubbles — Scene 2',
    type: 'Lettering',
    status: 'ASSIGNED',
    chapter: 'Ch. 13',
    chapterNumber: 13,
    series: 'Dragon\'s Ascent',
    deadline: daysFromNow(5),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Place and typeset dialogue bubbles for the temple dialogue scene. Use standard bubble style from style guide.',
    progress: 0,
  },
  {
    _id: 'AT-2405',
    title: 'Toning — Flashback Sequence',
    type: 'Toning',
    status: 'IN_PROGRESS',
    chapter: 'Ch. 10',
    chapterNumber: 10,
    series: 'Whispering Petals',
    deadline: daysFromNow(4),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Apply screen tones to flashback panels. Use 20% gray for memory panels, full white for present-day contrast.',
    progress: 30,
  },
];

export const APPROVED_TASKS: AssistantTask[] = [
  {
    _id: 'AT-2388',
    title: 'Panel Cleanup — Ep. 11',
    type: 'Cleanup',
    status: 'APPROVED',
    chapter: 'Ch. 11',
    chapterNumber: 11,
    series: 'Neon Genesis',
    deadline: daysAgo(5),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Final panel cleanup and white space adjustment.',
    progress: 100,
    pageCount: 4,
    earnings: 12000,
    submittedAt: daysAgo(7),
    approvedAt: daysAgo(5),
  },
  {
    _id: 'AT-2389',
    title: 'Screentone Application',
    type: 'Toning',
    status: 'APPROVED',
    chapter: 'Ch. 10',
    chapterNumber: 10,
    series: 'Cyberpunk Drifter',
    deadline: daysAgo(8),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Full chapter screentone pass.',
    progress: 100,
    pageCount: 6,
    earnings: 18000,
    submittedAt: daysAgo(10),
    approvedAt: daysAgo(8),
  },
  {
    _id: 'AT-2390',
    title: 'Character Flat Colors',
    type: 'Coloring',
    status: 'APPROVED',
    chapter: 'Ch. 9',
    chapterNumber: 9,
    series: 'Dragon\'s Ascent',
    deadline: daysAgo(12),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Flat color pass for main cast.',
    progress: 100,
    pageCount: 3,
    earnings: 9500,
    submittedAt: daysAgo(14),
    approvedAt: daysAgo(12),
  },
  {
    _id: 'AT-2391',
    title: 'Lettering — Final Pass',
    type: 'Lettering',
    status: 'APPROVED',
    chapter: 'Ch. 8',
    chapterNumber: 8,
    series: 'Whispering Petals',
    deadline: daysAgo(15),
    urgency: 'normal',
    assigneeName: 'Kenji Sato',
    assigneeAvatar: 'https://i.pravatar.cc/150?u=kenji',
    assigneeInitials: 'KS',
    description: 'Final lettering and SFX placement.',
    progress: 100,
    pageCount: 5,
    earnings: 14200,
    submittedAt: daysAgo(17),
    approvedAt: daysAgo(15),
  },
];

export const AI_TOOLS: AIToolConfig[] = [
  {
    id: 'sam',
    name: 'Sam',
    description: 'Segment & isolate manga panels automatically',
    color: 'text-violet-400',
    borderColor: 'border-violet-500/40',
    bgColor: 'bg-violet-500/10',
    defaultPrompt: 'Segment all character figures and speech bubbles on this page',
  },
  {
    id: 'yolo',
    name: 'Yolo',
    description: 'Detect objects, panels & speech regions',
    color: 'text-cyan-400',
    borderColor: 'border-cyan-500/40',
    bgColor: 'bg-cyan-500/10',
    defaultPrompt: 'Detect all panel borders and character bounding boxes',
  },
];

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000).toISOString();

export const MOCK_NOTIFICATIONS: AssistantNotification[] = [
  {
    _id: 'n1',
    type: 'task_assigned',
    actorName: 'Minh Tuấn',
    actorAvatar: 'https://i.pravatar.cc/150?u=mangaka',
    message: 'assigned you a new task: Background Lineart — Scene 3',
    taskId: 'AT-2401',
    createdAt: minutesAgo(12),
    read: false,
  },
  {
    _id: 'n2',
    type: 'task_revision',
    actorName: 'Minh Tuấn',
    actorAvatar: 'https://i.pravatar.cc/150?u=mangaka',
    message: 'requested revisions on Speed Lines & FX — check panel 3 feedback',
    taskId: 'AT-2403',
    createdAt: minutesAgo(45),
    read: false,
  },
  {
    _id: 'n3',
    type: 'deadline',
    actorName: 'System',
    actorAvatar: 'https://i.pravatar.cc/150?u=system',
    message: 'Deadline tomorrow for AT-2401 — Background Lineart is due in 1 day',
    taskId: 'AT-2401',
    createdAt: hoursAgo(2),
    read: false,
  },
  {
    _id: 'n4',
    type: 'task_approved',
    actorName: 'Minh Tuấn',
    actorAvatar: 'https://i.pravatar.cc/150?u=mangaka',
    message: 'approved your submission for Panel Cleanup — Ep. 11. ¥12,000 credited.',
    taskId: 'AT-2388',
    createdAt: hoursAgo(5),
    read: true,
  },
  {
    _id: 'n5',
    type: 'comment',
    actorName: 'Quốc Anh (Editor)',
    actorAvatar: 'https://i.pravatar.cc/150?u=editor',
    message: 'left a note on Character Inking — Hiro: "Line weight looks great on panel 2"',
    taskId: 'AT-2402',
    createdAt: hoursAgo(8),
    read: true,
  },
  {
    _id: 'n6',
    type: 'payment',
    actorName: 'Studio Finance',
    actorAvatar: 'https://i.pravatar.cc/150?u=finance',
    message: 'June earnings summary ready — ¥53,700 total from 4 approved tasks',
    createdAt: daysAgo(1),
    read: true,
  },
  {
    _id: 'n7',
    type: 'task_assigned',
    actorName: 'Minh Tuấn',
    actorAvatar: 'https://i.pravatar.cc/150?u=mangaka',
    message: 'assigned you Dialogue Bubbles — Scene 2 for Dragon\'s Ascent Ch. 13',
    taskId: 'AT-2404',
    createdAt: daysAgo(2),
    read: true,
  },
];
